name: party-classifier
language: Python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: reddit-raw
    required: true
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: mixed-classified
    required: true
  - name: labels
    inputType: FreeText
    description: List of parties to label. Delimiter is comma.
    defaultValue: 
    required: true
  - name: threshold
    inputType: FreeText
    description: Threshold in confidence to believe the model.
    defaultValue: 0.5
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
