name: Sentiment Analysis
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the raw data input topic
    defaultValue: reddit-raw
    required: true
  - name: output
    inputType: OutputTopic
    description: This is the output for the hugging face model score
    defaultValue: model-output
    required: true
  - name: openai_key
    inputType: Secret
    description: ''
    defaultValue: openai_key
    required: true
  - name: prompt
    inputType: FreeText
    description: ''
    defaultValue: "Analyze the sentiment of the following text: {comment}. Provide a sentiment score between -1 (very negative) and 1 (very positive) for Trump and Biden.  Judge also based on this text, chance of winning for both from -1 (losing) to 1 (winning). At any moment don't deviate from JSON schema and don't add any notes, just return JSON.  Provide the sentiment scores in the following JSON format: {{     \"Trump\": <sentiment_score>,      \"Biden\": <sentiment_score>,      \"Trump_winning\": <trump_winning_score>,     \"Biden_winning\": <biden_winning_score>,     \"confidence\": <confidence>     }}."
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
