name: sentiment-average
language: Python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: model-output
    required: false
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: metrics-1hour-average
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
