name: words-ranking
language: Python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: reddit-raw
    required: false
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: words-count
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
