name: reddit-source
language: Python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: reddit-raw
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
